//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger42915.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.AssignedTasks = new HashSet<AssignedTask>();
        }
    
        public int EmployeeID { get; set; }
        public string FullName { get; set; }
        public string MobileNo { get; set; }
    
        public virtual ICollection<AssignedTask> AssignedTasks { get; set; }
    }
}
